### ISSUE TITLE
Sugerencia: Incluir un botón que diga "Animar"

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2024-OlivaMarchetto-Buhler#11]
Debe incluirse un botón que diga "Animar".

Si bien al presionar "Calcular", la animación se reproduce, no hay forma de volver a verla.

**Comment by facu-olivam** [comment]
Hola profe, buenas tardes, decidí por cambiar la lógica del programa para que una vez presionado "Calcular", la animación se reproduzca en bucle.
