### ISSUE TITLE
CSS: Falta estilo por id

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2024-OlivaMarchetto-Buhler#20]
Falta el uso de al menos un estilo por id. Para ello deben emplear el #.
Ver ejemplo en la siguiente diapositiva: https://ucc-labcompu2.github.io/filminas/U4_CSS.html#/15

**Comment by facu-olivam** [comment]
Agregado en: 85282d733f0538863ce5bd21b18a1145a309aa2c , y b12a8de3cd1340d4386268ed30de9748bffc9b52
