### ISSUE TITLE
Emplear el atributo size para que el tamaño de los inputs sea prolijo

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/Proyecto2024-OlivaMarchetto-Buhler#7]

**Comment by facu-olivam** [comment]
El atributo size no funciona exactamente con inputs de tipo "number". De todas maneras, se redefinió su tamaño via estilos css.

https://www.w3schools.com/tags/att_input_size.asp - Note: The size attribute works with the following input types: text, search, tel, url, email, and password.
